#Установка порта
server:
  port: 8080

spring:
  cloud:
    gateway:
      # Говорится, что используется discovery
      discovery:
        locator:
          enabled: true
      defaultFilters:
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR
            statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, NOT_FOUND
            methods: GET
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: true

      # Настройка route(маршруты)
      routes:
        - id: events_service_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                patterns:
                  - /admin/categories/**
                  - /categories/**
                  - /admin/compilations/**
                  - /compilations/**
                  - /admin/events/**
                  - /users/{userId}/events/**
                  - /events/**
                  - /feign/events/**

        - id: ratings_service_route
          uri: lb://rating-service
          predicates:
            - Path=/events/{eventId}/rating, /users/{userId}/events/{eventId}/rating

        - id: requests_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /feign/requests/**

        - id: users_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

#Подключаем все эндпоинты Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

